("#!/usr/bin/env" #f #f #f)
(" " #f #f #f)
("swish" #f #f #f)
("\n" #f #f #f)
("\n" #f #f #f)
("(" #f #f lparen)
("define-syntax" keyword #f define-syntax)
(" " #f #f define-syntax)
("(" #f #f define-syntax+)
("my-thing" macro #f #f)
(" " #f #f #f)
("x" #f #f #f)
(")" #f #f #f)
("\n" #f #f #f)
("  " #f #f #f)
("(" #f #f lparen)
("syntax-case" keyword #f #f)
(" " #f #f #f)
("x" #f #f #f)
(" " #f #f #f)
("(" #f #f lparen)
(")" #f #f #f)
("\n" #f #f #f)
("    " #f #f #f)
("[" #f #f #f)
("(" #f #f lparen)
("_" #f #f #f)
(" " #f #f #f)
("abc" #f #f #f)
(")" #f #f #f)
("\n" #f #f #f)
("     " #f #f #f)
("#'" #f #f #f)
("(" #f #f lparen)
("begin" #f #f #f)
(" " #f #f #f)
("abc" #f #f #f)
(")" #f #f #f)
("]" #f #f #f)
(")" #f #f #f)
(")" #f #f #f)
("\n" #f #f #f)
("\n" #f #f #f)
("(" #f #f lparen)
("define-syntax" keyword #f define-syntax)
(" " #f #f define-syntax)
("other-thing" macro #f #f)
("\n" #f #f #f)
("  " #f #f #f)
("(" #f #f lparen)
("syntax-rules" keyword #f #f)
(" " #f #f #f)
("(" #f #f lparen)
(")" #f #f #f)
("\n" #f #f #f)
("    " #f #f #f)
("[" #f #f #f)
("(" #f #f lparen)
("_" #f #f #f)
(" " #f #f #f)
("abc" #f #f #f)
(")" #f #f #f)
("\n" #f #f #f)
("     " #f #f #f)
("(" #f #f lparen)
("begin" #f #f #f)
(" " #f #f #f)
("abc" #f #f #f)
(")" #f #f #f)
("]" #f #f #f)
(")" #f #f #f)
(")" #f #f #f)
("\n" #f #f #f)
("\n" #f #f #f)
("(" #f #f lparen)
("meta" macro #f #f)
(" " #f #f #f)
("define" #f #f #f)
(" " #f #f #f)
("(" #f #f lparen)
("->spec" #f #f #f)
(" " #f #f #f)
("x" #f #f #f)
(")" #f #f #f)
("\n" #f #f #f)
("  " #f #f #f)
("body" #f #f #f)
(" " #f #f #f)
("..." #f #f #f)
(")" #f #f #f)
("\n" #f #f #f)
("\n" #f #f #f)
("(" #f #f lparen)
("meta" macro #f #f)
(" " #f #f #f)
("define" #f #f #f)
(" " #f #f #f)
("->spec" #f #f #f)
("\n" #f #f #f)
("  " #f #f #f)
("(" #f #f lparen)
("lambda" keyword #f #f)
(" " #f #f #f)
("(" #f #f lparen)
("x" #f #f #f)
(")" #f #f #f)
("\n" #f #f #f)
("    " #f #f #f)
("body" #f #f #f)
(" " #f #f #f)
("..." #f #f #f)
(")" #f #f #f)
(")" #f #f #f)
("\n" #f #f #f)
("\n" #f #f #f)
("(" #f #f lparen)
("define" keyword #f define)
(" " #f #f define)
("x" variable #f #f)
(" " #f #f #f)
("(" #f #f lparen)
("lambda" keyword #f #f)
(" " #f #f #f)
("(" #f #f lparen)
("y" #f #f #f)
(" " #f #f #f)
("z" #f #f #f)
(")" #f #f #f)
(" " #f #f #f)
("body" #f #f #f)
(" " #f #f #f)
("..." #f #f #f)
(")" #f #f #f)
(")" #f #f #f)
("\n" #f #f #f)
("\n" #f #f #f)
("(" #f #f lparen)
("define" keyword #f define)
(" " #f #f define)
("(" #f #f define+)
("x" function #f #f)
(" " #f #f #f)
("y" #f #f #f)
(" " #f #f #f)
("z" #f #f #f)
(")" #f #f #f)
(" " #f #f #f)
("body" #f #f #f)
(" " #f #f #f)
("..." #f #f #f)
(")" #f #f #f)
("\n" #f #f #f)
("\n" #f #f #f)
("11" number #f #f)
(" " #f #f #f)
("\"this is a \\\n long string \\\n that is on \\\n multiple lines.\"" string #f #f)
(" " #f #f #f)
("14" number #f #f)
("\n" #f #f #f)
("\n" #f #f #f)
("(" #f #f lparen)
("re" #f #f regexp)
(" " #f #f regexp)
("\"this is a regexp\"" regexp #f #f)
(")" #f #f #f)
("\n" #f #f #f)
("\n" #f #f #f)
("(" #f #f lparen)
("pregexp-match" #f #f regexp)
(" " #f #f regexp)
("\"a regexp\"" regexp #f #f)
(" " #f #f #f)
("\"this is a string\"" string #f #f)
(")" #f #f #f)
("\n" #f #f #f)
("\n" #f #f #f)
("(" #f #f lparen)
("let" keyword #f let)
(" " #f #f let)
("lp" function #f #f)
(" " #f #f #f)
("(" #f #f lparen)
("[" #f #f #f)
("x" #f #f #f)
(" " #f #f #f)
("12" number #f #f)
("]" #f #f #f)
("\n" #f #f #f)
("         " #f #f #f)
("[" #f #f #f)
("y" #f #f #f)
(" " #f #f #f)
("13" number #f #f)
("]" #f #f #f)
(")" #f #f #f)
("\n" #f #f #f)
("  " #f #f #f)
("(" #f #f lparen)
("let" keyword #f let)
(" " #f #f let)
("(" #f #f lparen)
("[" #f #f #f)
("x" #f #f #f)
(" " #f #f #f)
("y" #f #f #f)
("]" #f #f #f)
("\n" #f #f #f)
("        " #f #f #f)
("[" #f #f #f)
("y" #f #f #f)
(" " #f #f #f)
("x" #f #f #f)
("]" #f #f #f)
(")" #f #f #f)
("\n" #f #f #f)
("    " #f #f #f)
("(" #f #f lparen)
("+" #f #f #f)
(" " #f #f #f)
("x" #f #f #f)
(" " #f #f #f)
("y" #f #f #f)
(")" #f #f #f)
(")" #f #f #f)
(")" #f #f #f)
("\n" #f #f #f)
("\n" #f #f #f)
("(" #f #f lparen)
("set!" function (side-effect) #f)
(" " #f #f #f)
("foo" #f #f #f)
(" " #f #f #f)
("(" #f #f lparen)
("#2%car" function (optimize2) #f)
(" " #f #f #f)
("(" #f #f lparen)
("#3%cdr" function (optimize3) #f)
(" " #f #f #f)
("(" #f #f lparen)
("#%$enum-set-members" function (internal) #f)
(")" #f #f #f)
(")" #f #f #f)
(")" #f #f #f)
(")" #f #f #f)
("\n" #f #f #f)
("\n" #f #f #f)
("(" #f #f lparen)
("vector-sort!" function (side-effect) #f)
(" " #f #f #f)
("v" #f #f #f)
(")" #f #f #f)
("\n" #f #f #f)
("(" #f #f lparen)
("append!" function (side-effect) #f)
(" " #f #f #f)
("ls" #f #f #f)
(")" #f #f #f)
("\n" #f #f #f)
("\n" #f #f #f)
("(" #f #f lparen)
("#3%vector-sort!" function (optimize3 side-effect) #f)
(" " #f #f #f)
("abc" #f #f #f)
(")" #f #f #f)
("\n" #f #f #f)
("\n" #f #f #f)
("(" #f #f lparen)
("define-tuple" keyword #f define)
(" " #f #f define)
("<point>" type #f #f)
(" " #f #f #f)
("x" #f #f #f)
(" " #f #f #f)
("y" #f #f #f)
(")" #f #f #f)
("      " #f #f #f)
("; What color should <point> have been?" comment #f #f)
("\n" #f #f #f)
("(" #f #f lparen)
("<point>" type #f #f)
(" " #f #f #f)
("make" #f #f #f)
(" " #f #f #f)
("[" #f #f #f)
("x" #f #f #f)
(" " #f #f #f)
("1" number #f #f)
("]" #f #f #f)
(" " #f #f #f)
("[" #f #f #f)
("y" #f #f #f)
(" " #f #f #f)
("2" number #f #f)
("]" #f #f #f)
(")" #f #f #f)
("\n" #f #f #f)
("\n" #f #f #f)
("(" #f #f lparen)
("define" keyword #f define)
(" " #f #f define)
("eol" variable #f #f)
(" " #f #f #f)
("#\\newline" string #f #f)
(")" #f #f #f)
("\n" #f #f #f)
